"""auto update

Revision ID: 51cc7331691e
Revises: 
Create Date: 2026-09-02 04:17:55.393118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51cc7331691e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atom_projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('project_key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('requirement', sa.String(), nullable=True),
    sa.Column('app_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('building_at', sa.Integer(), nullable=True),
    sa.Column('revisions', sa.String(), nullable=True),
    sa.Column('versions', sa.String(), nullable=True),
    sa.Column('active_ver', sa.Integer(), nullable=True),
    sa.Column('client_created_at', sa.Integer(), nullable=True),
    sa.Column('client_updated_at', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_atom_projects_id'), 'atom_projects', ['id'], unique=False)
    op.create_index(op.f('ix_atom_projects_user_id'), 'atom_projects', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_atom_projects_user_id'), table_name='atom_projects')
    op.drop_index(op.f('ix_atom_projects_id'), table_name='atom_projects')
    op.drop_table('atom_projects')
    # ### end Alembic commands ###